# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EXqz4h0kN7j05mFHOXoc3eDutfYEq0nB
"""

mynum

mynum = 6


guess  = int(input('Enter a number between 0 and 15:'))
count = 1
while guess != mynum and count < 5:
    if guess <mynum:
        print("Too low")
    else:
        print("Too High")
   


    guess  = int(input('Enter a number between 0 and 15:'))
    count = count +1 

if guess == mynum:
    print("Excellent,you found it", mynum)
else:
    print("Loser, you didn't got the number")
print('Your trials =  ', count)

import turtle

turtle.shape("Turtle")
x = 0
for x in range(50):
    for i in range(5):
        turtle.forward(100+x)
        turtle.right(90)
    turtle.right(6)
    x = x + 30